services:
  ml-bridge:
    build:
      context: ..
      dockerfile: infra/docker/ml-bridge/Dockerfile
    container_name: ml-bridge
    environment:
      MLBRIDGE_CONFIG: /app/config/models.yaml
      SUBPROC_TIMEOUT: 15
    volumes:
      - ../apps/ml-bridge:/app
    ports:
      - "7000:7000"

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  rag:
    build:
      context: ..
      dockerfile: infra/docker/rag-service/Dockerfile
    container_name: rag
    env_file:
      - ../.env
    environment:
      USER_AGENT: "kfh-rag/1.0"
    volumes:
      - ../apps/rag-service:/app
      - ../configs:/configs:ro
      #- ../.env:/app/.env:ro
      - ../chroma_db:/app/chroma_db
    depends_on:
      - redis
    ports:
      - "8002:8002"

  gateway:
    build:
      context: ..
      dockerfile: infra/docker/gateway/Dockerfile
    container_name: gateway
    env_file:
      - ../.env
    volumes:
      - ../apps/gateway:/app
    depends_on:
      - rag
      - advisor
      - report
    ports:
      - "8000:8000"

  advisor:
    build:
      context: ..
      dockerfile: infra/docker/advisor-service/Dockerfile
    container_name: advisor
    env_file:
      - ../.env
    volumes:
      - ../apps/advisor-service:/app
    depends_on:
      - market
      - ml-bridge
    ports:
      - "8003:8003"

  report:
    build:
      context: ..
      dockerfile: infra/docker/report-service/Dockerfile
    container_name: report
    env_file:
      - ../.env
    volumes:
      - ../apps/report-service:/app
    ports:
      - "8004:8004"

  market:
    build:
      context: ..
      dockerfile: infra/docker/market-service/Dockerfile
    container_name: market
    env_file:
      - ../.env
    volumes:
      - ../apps/market-service:/app
    depends_on:
      - redis
    ports:
      - "8005:8005"

  ui:
    build:
      context: ..
      dockerfile: infra/docker/ui/Dockerfile
    container_name: ui
    env_file:
      - ../.env
    volumes:
      - ../apps/ui:/app
      - ../apps/ui/data:/app/data:ro
      - ../apps/ui/data/train.csv:/app/data/train.csv:ro
    depends_on:
      - gateway
    ports:
      - "8501:8501"

volumes:
  chroma_db:


